### ISSUE TITLE
Selenium IDE pluggins SeLite Run All Favorites error

### ISSUE THREAD

**Issue by Tazz07** [SeLite/SeLite#10]
Hello, i have some problems about installation of Selenium IDE & some pluggins, on a new machine Windows7, with Firefox 42.0 & Selenium IDE 2.9.0. My first one machine works with no problem, with all plugins i want. I make the same steps for the 2nd one so an error appear.

When i begin selenium, an error poping. I think it's in link with incompatibility of plugins : Favorites & SeLite Run All Favorites error (see linked picture). Perhaps with some recent upgrades of firefox or pluggins, makes appear this conflict, or perhaps a specific order of set up concerning pluggins.
Finally the option "Run all favorites", use for chain some tests series is not present, and Favorites options are unusable.
Perhaps i do something wrong, someone can help me ?

For information the error (text):
" There was an unexpected error. Msg: Error: Root folders of parameter file and folderRelativeTo don't match.
Url: chrome://selite-run-all-favorites/content/extensions/run-all-favorites.js?1447084272514, line: 47, column: 1
getRelativePath@chrome://selite-run-all-favorites/content/extensions/run-all-favorites.js?1447084272514:47:1
getRelativePathToHome@chrome://selite-run-all-favorites/content/extensions/run-all-favorites.js?1447084272514:73:20
@chrome://selite-run-all-favorites/content/extensions/run-all-favorites.js?1447084272514:112:32"

![pb selenium module slraf2](https://cloud.githubusercontent.com/assets/15731738/11057444/5a390eaa-878b-11e5-9977-115992a4f5ab.png)

**Comment by Tazz07** [comment]
For a complement of informations i download pluggins only verified by firefox.
The list of pluggin :
- Favorites (Selenium IDE)
- File Logging (Selenium IDE)
- Highlight Elements (Selenium IDE)
- ScreenShot on Fail (Selenium IDE)
- Selenium Expert (Selenium IDE)
- Selenium IDE
- Selenium IDE: Flow Control
- Selenium IDE: Implicit Wait
- SeLite Extension Sequencer
- SeLite Run All Favorites
- Stored Variables (Selenium IDE)
- Test Results (Selenium IDE)

**Comment by Tazz07** [comment]
And what i Waiting For it's all this melt works together. I think the initial problem comes from "SeLite Run All Favorites". Perhaps a specific order of installation with pluggins ... don't know exactly yet. So it's why i need your precious help. If you need more informations, don't hesitate.

**Comment by peter-kehl** [comment]
Hi Tazz,

Thank you for reporting this. Apologies for my delay. I was overloaded in November and then I traveled for over a month.

The only scenario when this could happen is: You imported (or had existing) favorites (test cases), and one or more of them are outside of your home folder. Can that be the case?

Please, would you visit Firefox special URL about:config. Then enter preference name extensions.selenium-ide.plugin.favorites.favorites. Send me its value (or post it here).

Open Firefox URL about:config, set property devtools.chrome.enabled to boolean true. Restart Firefox. Then click  menu Tools > Web Developer > Scratchpad. (See also http://selite.github.io/DevelopmentTools).

In Scratchpad's menu, click Environment > Browser. Then enter in Scratchpad:
alert(Components.classes["@mozilla.org/file/directory_service;1"].getService(Components.interfaces.nsIProperties).get("Home", Components.interfaces.nsIFile).path ) 

then click button 'Run'. It should show your home folder (for Firefox). What is it?

**Comment by Tazz07** [comment]
Hi Peter,
First thank you for your answer and your works, this is very useful for me ,
Secondly I don’t waiting for find specific solution, and I already uninstall all plugins and clear all selenium config, and make a new installation of plugins.

At the moment extensions.selenium-ide.plugin.favorites.favorites have no value, empty value. Perhaps because I have deactivate the plugin “run all favorites”.
But I hoped to find a solution quickly to launch several Tests Suites successively.

I don’t have any menu “web developer”. Perhaps only with activation of plugin run all favorites ?


For your answer, yes I have some tests cases, all are separated in a specific folder, but they have all the same folder root.
For example :
C:\Main Folder__ALL Tests Cases
On you have some specific tests cases like this :
C:\Main Folder__ALL Tests Cases\Test Case A\ …
C:\Main Folder__ALL Tests Cases\Test Case B\ …

Or some tests cases with deeper folder like this :
C:\Main Folder__ALL Tests Cases\Product A\Test case 1
C:\Main Folder__ALL Tests Cases\Product A\Test case 2
C:\Main Folder__ALL Tests Cases\Test Case B\Test case 3

In what configuration of folder I can’t have problem with plugins “run all favorites”? Same question for have problem.
Or perhaps you can explain me how the value of home folder can change.


Sincerely,
TAZ

De : Peter Kehl [mailto:notifications@github.com]
Envoyé : mardi 12 janvier 2016 08:29
À : SeLite/SeLite <SeLite@noreply.github.com>
Cc : Thibault AZZOPARDI <thibault.azzopardi@itinsell.com>
Objet : Re: [SeLite] Selenium IDE pluggins SeLite Run All Favorites error (#10)


Hi Tazz,

Thank you for reporting this. Apologies for my delay. I was overloaded in November and then I traveled for over a month.

The only scenario when this could happen is: You imported (or had existing) favorites (test cases), and one or more of them are outside of your home folder. Can that be the case?

Please, would you visit Firefox special URL about:config. Then enter preference name extensions.selenium-ide.plugin.favorites.favorites. Send me its value (or post it here).

Open Firefox URL about:config, set property devtools.chrome.enabled to boolean true. Restart Firefox. Then click menu Tools > Web Developer > Scratchpad. (See also http://selite.github.io/DevelopmentTools).

In Scratchpad's menu, click Environment > Browser. Then enter in Scratchpad:
alert(Components.classes["@mozilla.org/file/directory_service;1"].getService(Components.interfaces.nsIProperties).get("Home", Components.interfaces.nsIFile).path )

then click button 'Run'. It should show your home folder (for Firefox). What is it?

**Comment by peter-kehl** [comment]
Hi Taz,

In order to see "Web Developer" menu, open Firefox special URL about:config. Enter name of configuration field devtools.chrome.enabled, and set it to true. Then follow the rest of the above steps. 

Alternatively, get your home folder by running Windows start menu > Run: cmd > echo %USERPROFILE%

Run All Favorites requires that all your favorite test cases are under your home folder, or relative to it. It means that they all have to be on the same volume (drive - C:, D:, E:...) as your home folder. Is it so?

After I installed Run All Favorites, extensions.selenium-ide.plugin.favorites.favorites was empty (not set). When I add and remove a favorite, then it becomes a string value '[]'.

**Comment by peter-kehl** [comment]
I've updated Run All Favorites, so that it reports more details on your problem. Download it from https://addons.mozilla.org/en-US/firefox/addon/selite-run-all-favorites/versions/.

**Comment by Tazz07** [comment]
Hi Peter,
Apparently my home folder is : C:\Users\TAP
And all my test cases are packed in folder : D:\SVN

So you make the point on the obvious part.
So the next step is how merge the two ?
1) How you change path for my home folder ?
2) Or I need to move all my test cases, if 1) impossible.

Sincerely,


De : Peter Kehl [mailto:notifications@github.com]
Envoyé : mardi 12 janvier 2016 21:49
À : SeLite/SeLite <SeLite@noreply.github.com>
Cc : Thibault AZZOPARDI <thibault.azzopardi@itinsell.com>
Objet : Re: [SeLite] Selenium IDE pluggins SeLite Run All Favorites error (#10)


Hi Taz,

In order to see "Web Developer" menu, open Firefox special URL about:config. Enter name of configuration field devtools.chrome.enabled, and set it to true. Then follow the rest of the above steps.

Alternatively, get your home folder by running Windows start menu > Run: cmd > echo %USERPROFILE%

Run All Favorites requires that all your favorite test cases are under your home folder, or relative to it. It means that they all have to be on the same volume (drive - C:, D:, E:...) as your home folder. Is it so?

After I installed Run All Favorites, extensions.selenium-ide.plugin.favorites.favorites was empty (not set). When I add and remove a favorite, then it becomes a string value '[]'.

**Comment by peter-kehl** [comment]
Hi Thibault,

You can't and don't  want to change your home folder-  it ties with your Windows profile.  So you need to move both your test suites and test cases on the same volume- C:.

-Peter Kehl

**Comment by Tazz07** [comment]
Hi Peter,
Ok I will apply your advice, and move all in C :, if it solves my problem, I have no choice.

So thank you, to take time for solve my problem.
I will test this, and you will have return soon.


De : Peter Kehl [mailto:notifications@github.com]
Envoyé : jeudi 14 janvier 2016 10:18
À : SeLite/SeLite <SeLite@noreply.github.com>
Cc : Thibault AZZOPARDI <thibault.azzopardi@itinsell.com>
Objet : Re: [SeLite] Selenium IDE pluggins SeLite Run All Favorites error (#10)


Hi Thibault,

You can't and don't want to change your home folder- it ties with your Windows profile. So you need to move both your test suites and test cases on the same volume- C:.

-Peter Kehl

**Comment by peter-kehl** [comment]
I've uploaded a new version of Run All Favorites. It will allow test suites to be outside the home folder.

Thank you for your feedback.

**Comment by Tazz07** [comment]
No problem my dear,
Honnor is for you first ;)
Ty for your up.

Sincerely,
Taz

**Comment by Tazz07** [comment]
Hi peter,
So your current version allow only in same home folder C:.
It’s not very user-friendly because generally C: is only use for running Operating System. So if you want to keep yours suites updated, you will deteriorate more efficiently your hard disk.
So I think it will be good to allow other data drive.
Sincerely,

**Comment by peter-kehl** [comment]
As I have mentioned above: I've uploaded a new version of Run All Favorites (0.14). It allows test suites to be outside the home folder (or on any Windows drive).

**Comment by Tazz07** [comment]
Ok, I don’t remember I not refresh my plugins automatically. So I will test this. Thank you.
