### ISSUE TITLE
Clipboard And Indent: Recording fails

### ISSUE THREAD

**Issue by mirao** [SeLite/SeLite#13]
### Steps:

- Install the full set of SeLite addons: https://addons.mozilla.org/en-US/firefox/addon/selite/
- Open Selenium IDE
- Create a new test suite
- Click on "Click to record"
- Open http://www.seleniumhq.org/
- Switch between some tabs on that page
- Enter "IDE" into search and press Enter or click on Go

### Expected result:
- no error, the actions are recorded

### Actual result:
- no action is recorded (BUG)
- IDE throws this error (BUG):

`There was an unexpected error. Msg: TypeError: can't assign to properties of (new String("open")): not an object
Url: chrome://selite-clipboard-and-indent/content/extensions/clipboard-and-indent-ide.js?1486206013814, line: 286, column: 7
Editor.prototype.addCommand@chrome://selite-clipboard-and-indent/content/extensions/clipboard-and-indent-ide.js?1486206013814:286:7
Editor.prototype.addCommand@chrome://selite-clipboard-and-indent/content/extensions/clipboard-and-indent-ide.js?1486206013814:228:11
Recorder.prototype.record@chrome://selenium-ide/content/recorder.js:160:4
@chrome://selenium-ide/content/recorder-handlers.js:28:9
Recorder.prototype.attach/register/listener@chrome://selenium-ide/content/recorder.js:128:7`

If you remove the addon "SeLite Clipboard And Indent", it works well.

### Used SW:

- Ubuntu 16.10
- Firefox 51.0.1
- Selenium IDE 2.9.1.1
- SeLite 0.09
- SeLite Clipboard And Indent 0.23

**Comment by peter-lyons-kehl** [comment]
Unfortunately, new Selenium IDE doesn't support extensions as much. It is too restrictive.

Please, influence https://github.com/SeleniumHQ/selenium-ide. Ask that they load extension scripts in their scope. Only then SeLite and community add-ons can extend actions.
