### ISSUE TITLE
RE: Goto and While not working in Rollups

### ISSUE THREAD

**Issue by peter-kehl** [SeLite/SeLite#15]
Hi @AnswerWas42,

You may benefit from SelBlocksGlobal, which is a part of @SeLite. (Like SelBlocks, it won't work with Rollups & sideflow.js either. However, it allows you to reuse functions across test cases.)

See https://selite.github.io.

**Comment by AnswerWas42** [comment]
Thanks Peter, I was using rollups as a global function capability, er, well trying to use.   SelBlocksGlobal would provide reusable functions that I can store as a library it would make storing code much easier.

**Comment by peter-lyons-kehl** [comment]
Hi Don,

Unfortunately, new Selenium IDE doesn't support extensions as much. It is too restrictive.

Please, influence https://github.com/SeleniumHQ/selenium-ide. Ask that they load extension scripts in their scope. Only then SeLite and community add-ons can extend actions.
