### ISSUE TITLE
More power to you and users of Selenium IDE

### ISSUE THREAD

**Issue by peter-lyons-kehl** [SeLite/SeLite#18]
Dear @Jongkeun,

Good that you're using new Selenium IDE.

Its users used to get even more power from a family of extensions: SeLite.github.io. However, because of new Firefox API, SeLite needs moral support. Let's connect to help people benefit further.

**Comment by Jongkeun** [comment]
First of all, Thanks to mention me.
Secondly, I’m very sorry about that I haven't heard about SeLite.
So I haven't known what SeLite is for.
But I will try to analyze how to use and working it.
I'll do it to the best of my ability.
Tell me about something that I can help you in detail

**Comment by Jongkeun** [comment]
For now, new Selenium IDE is not working properly on Firefox.
So we should fix it first.

**Comment by pgroot91** [comment]
Will be following **Selenium IDE** and the **SeLite** project from a tester perspective. Hope the functionality is going to make it to the new IDE in near feature.
